library(httr)
library(jsonlite)
library(base64enc)
library(digest)

your_key <- "6e2748d54670f802cf50ad872676e6bb"
your_secret <- "RS1XszjtYmOLVzaqY4TpW40G8FZkLrqANQB6zG2CF/CSD5hET6bAKiISb4NBSaSXTMWgNFN+iijlf4jDnSxtmw=="
your_passphrase <- "eglvainbnaw"

endpointURL <- "https://api-public.sandbox.pro.coinbase.com"


# function to provide authentication without a body "GET" request
Authentication_GET <- function(request){
  
  timestamp <- format(as.numeric(Sys.time()), digits=13) # generates number of sec since Unix Epoch in UTC
  
  message <- paste0(timestamp, "GET/" , request) # generates message used for decoding
  
  hmac_key <- base64decode(your_secret) # base 64 decode secret key given by coinbasepro API
  
  signature_64 <-base64_enc(hmac(hmac_key, message, algo = "sha256", raw = TRUE)) # generates HASH
  
  return(signature_64)
}

#function to provide authentication with a body "POST" request
Authentication_body_POST <- function(request, body){
  
  timestamp <- format(as.numeric(Sys.time()), digits=13) # generates number of sec since Unix Epoch in UTC
  
  message <- paste0(timestamp, "POST/", request, body) # generates message used for decoding
  
  hmac_key <- base64decode(your_secret) # base 64 decode secret key given by coinbasepro API
  
  signature_64 <-base64_enc(hmac(hmac_key, message, algo = "sha256", raw = TRUE)) # generates HASH
  
  return(signature_64)
}

#function to provide authentication with a body "DELETE" request
Authentication_DELETE <- function(request){
  timestamp <- format(as.numeric(Sys.time()), digits=13) # generates number of sec since Unix Epoch in UTC
  
  message <- paste0(timestamp, "DELETE/" , request) # generates message used for decoding
  
  hmac_key <- base64decode(your_secret) # base 64 decode secret key given by coinbasepro API
  
  signature_64 <-base64_enc(hmac(hmac_key, message, algo = "sha256", raw = TRUE)) # generates HASH
  
  return(signature_64)
}

#function to return accounts information
accounts <- function(){
  cb_timestamp <- format(as.numeric(Sys.time()), digits=13) # generates number of sec since Unix Epoch in UTC
  # must match time generated by authentication
  Secret_64 <- Authentication_GET("accounts") # generates Authentication hash
  
  # Executes GET request for account details
  AccountDetails <- GET(paste0(endpointURL, "/accounts"), add_headers('CB-ACCESS-KEY' = your_key, 'CB-ACCESS-SIGN' = Secret_64, 
                                                                      'CB-ACCESS-TIMESTAMP' = cb_timestamp, 'CB-ACCESS-PASSPHRASE' = your_passphrase, 
                                                                      'Content-Type'='application/json'))
  content <- content(AccountDetails)  # Stores content from the GET request
  
  return(content)
  
}

#function to get list of exchanges on CoinbasePro
get_product <- function(){
  
  AccountDetails <- GET(paste0(endpointURL, "/products"))
  content <- content(AccountDetails)  
  
  return(content)  
  
}

#function to get a products current price example product_id = "BTC-USD"
get_product_ticker <- function(product_id){
  
  
  AccountDetails <- GET(paste0(endpointURL, "/products/", product_id, "/ticker"))
  content <- content(AccountDetails)  
  
  return(content)   
  
}

# function to execute a market order(Got the function to successfully post the request)
market_order <- function(amount, buy_or_sell, product_id, size_or_funds = c("size", "funds")){
  # amount = amount of crypto to buy or sell, or amount of money to buy with or sell to obtain.
  # buy_or_sell = whether to buy or sell crypto
  # product_id = product to buy or sell example: "BTC-USD"
  # size_or_funds = weather to use amount of crypto or amount of USD to buy or sell
  cb_timestamp <- format(as.numeric(Sys.time()), digits=13) # generates number of sec since Unix Epoch in UTC
  # must match time generated by authentication
  
  # creates string in JSON form to create a market order
  if(size_or_funds == "size"){
    MarketOrderJSON <- paste0("{\n\"size\":\"", amount, "\",\"side\":\"", buy_or_sell, "\",\"product_id\":\"", product_id, "\",\"type\": \"market\"\n}")
  }
  
  if(size_or_funds == "funds"){
    MarketOrderJSON <- paste0("{\n\"funds\":\"", amount, "\",\"side\":\"", buy_or_sell, "\",\"product_id\":\"", product_id, "\",\"type\": \"market\"\n}")
  }
  
  Secret_64 <- Authentication_body_POST("orders", MarketOrderJSON) #creates authentication HASH
  
  AccountDetails <- POST(paste0(endpointURL, "/orders"), body = MarketOrderJSON ,add_headers('CB-ACCESS-KEY' = your_key, 'CB-ACCESS-SIGN' = Secret_64, 
                                                                                             'CB-ACCESS-TIMESTAMP' = cb_timestamp, 'CB-ACCESS-PASSPHRASE' = your_passphrase, 
                                                                                             'Content-Type'='application/json'))
  content <- content(AccountDetails)  
  
  return(content)  
  
}

# function to get EPOCh time or iso time
get_time <- function(){
  
  AccountDetails <- GET(paste0(endpointURL, "/time"))
  content <- content(AccountDetails)  
  
  return(content)  
  
}

# function to cancel all open orders
cancel_all <- function(){
  cb_timestamp <- format(as.numeric(Sys.time()), digits=13) # generates number of sec since Unix Epoch in UTC
  # must match time generated by authentication
  Secret_64 <- Authentication_DELETE("orders") # generates Authentication hash
  
  # Executes GET request for account details
  AccountDetails <- DELETE(paste0(endpointURL, "/orders"), add_headers('CB-ACCESS-KEY' = your_key, 'CB-ACCESS-SIGN' = Secret_64, 
                                                                       'CB-ACCESS-TIMESTAMP' = cb_timestamp, 'CB-ACCESS-PASSPHRASE' = your_passphrase, 
                                                                       'Content-Type'='application/json'))
  content <- content(AccountDetails)  # Stores content from the GET request
  
  return(content)
}


########################################## function test ZONE
